var HeirloomStats = {
    "values": [
      10,
      20,
      30,
      50,
      150,
      300,
      800,
      2000,
      5000,
      15000,
      100000
    ],
    "recycleOverride": [
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      250000,
      1000000
    ],
    "slots": [
      1,
      2,
      3,
      3,
      3,
      4,
      4,
      5,
      5,
      6,
      6
    ],
    "defaultSteps": [
      [
        3,
        6,
        1
      ],
      [
        3,
        6,
        1
      ],
      [
        3,
        6,
        1
      ],
      [
        6,
        12,
        1
      ],
      [
        16,
        40,
        2
      ],
      [
        32,
        80,
        4
      ],
      [
        64,
        160,
        8
      ],
      [
        128,
        320,
        16
      ],
      [
        256,
        640,
        32
      ],
      [
        512,
        1280,
        64
      ],
      [
        1024,
        2560,
        128
      ]
    ],
    "rarityNames": [
      "Common",
      "Uncommon",
      "Rare",
      "Epic",
      "Legendary",
      "Magnificent",
      "Ethereal",
      "Magmatic",
      "Plagued",
      "Radiating",
      "Hazardous"
    ],
    "rarities": [
      [
        5000,
        3500,
        1500,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1
      ],
      [
        1000,
        5000,
        4000,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1
      ],
      [
        -1,
        3500,
        5000,
        1500,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1
      ],
      [
        -1,
        2000,
        4000,
        4000,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1
      ],
      [
        -1,
        1500,
        3000,
        5000,
        500,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1
      ],
      [
        -1,
        800,
        2000,
        6000,
        1000,
        200,
        -1,
        -1,
        -1,
        -1,
        -1
      ],
      [
        -1,
        400,
        1000,
        7000,
        1000,
        500,
        100,
        -1,
        -1,
        -1,
        -1
      ],
      [
        -1,
        200,
        500,
        6000,
        2200,
        800,
        300,
        -1,
        -1,
        -1,
        -1
      ],
      [
        -1,
        -1,
        -1,
        5000,
        3000,
        1700,
        300,
        -1,
        -1,
        -1,
        -1
      ],
      [
        -1,
        -1,
        -1,
        2500,
        5000,
        2000,
        500,
        -1,
        -1,
        -1,
        -1
      ],
      [
        -1,
        -1,
        -1,
        -1,
        7000,
        2400,
        500,
        100,
        -1,
        -1,
        -1
      ],
      [
        -1,
        -1,
        -1,
        -1,
        6000,
        3170,
        680,
        150,
        -1,
        -1,
        -1
      ],
      [
        -1,
        -1,
        -1,
        -1,
        3000,
        5000,
        1650,
        350,
        -1,
        -1,
        -1
      ],
      [
        -1,
        -1,
        -1,
        -1,
        -1,
        4500,
        3000,
        2000,
        500,
        -1,
        -1
      ],
      [
        -1,
        -1,
        -1,
        -1,
        -1,
        1500,
        2000,
        5000,
        1500,
        -1,
        -1
      ],
      [
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        1000,
        6000,
        3000,
        -1,
        -1
      ],
      [
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        7500,
        2500,
        -1
      ],
      [
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        5000,
        5000,
        -1
      ],
      [
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        10000,
        -1
      ],
      [
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        8500,
        1500
      ],
      [
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        7000,
        3000
      ],
      [
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        3000,
        7000
      ]
    ],
    "rarityBreakpoints": [
      41,
      60,
      80,
      100,
      125,
      146,
      166,
      181,
      201,
      230,
      300,
      400,
      500,
      600,
      700,
      1,
      40,
      80,
      100,
      135,
      175
    ],
    "universeBreakpoints": [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      2,
      2,
      2,
      2,
      2,
      2
    ],
    "priceIncrease": [
      1.5,
      1.5,
      1.25,
      1.19,
      1.15,
      1.12,
      1.1,
      1.06,
      1.04,
      1.03,
      1.02
    ],
    "canReplaceMods": [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      false,
      false,
      false
    ],
    "Core": {
      "fireTrap": {
        "name": "Fire Trap Damage",
        "currentBonus": 0,
        "steps": [
          [
            10,
            25,
            1
          ],
          [
            10,
            25,
            1
          ],
          [
            10,
            25,
            1
          ],
          [
            25,
            50,
            1
          ],
          [
            50,
            100,
            2
          ],
          [
            100,
            199,
            3
          ],
          [
            200,
            400,
            4
          ]
        ]
      },
      "poisonTrap": {
        "name": "Poison Trap Damage",
        "currentBonus": 196,
        "steps": [
          -1,
          [
            10,
            25,
            1
          ],
          [
            10,
            25,
            1
          ],
          [
            25,
            50,
            1
          ],
          [
            50,
            100,
            2
          ],
          [
            100,
            199,
            3
          ],
          [
            200,
            400,
            4
          ]
        ]
      },
      "lightningTrap": {
        "name": "Lightning Trap Damage",
        "currentBonus": 50,
        "steps": [
          -1,
          -1,
          [
            1,
            10,
            1
          ],
          [
            10,
            20,
            1
          ],
          [
            20,
            50,
            2
          ],
          [
            50,
            100,
            2
          ],
          [
            100,
            199,
            3
          ]
        ]
      },
      "runestones": {
        "name": "Runestone Drop Rate",
        "currentBonus": 133,
        "steps": [
          [
            10,
            25,
            1
          ],
          [
            10,
            25,
            1
          ],
          [
            10,
            25,
            1
          ],
          [
            25,
            50,
            1
          ],
          [
            50,
            100,
            2
          ],
          [
            100,
            199,
            3
          ],
          [
            200,
            400,
            4
          ]
        ]
      },
      "strengthEffect": {
        "name": "Strength Tower Effect",
        "currentBonus": 0,
        "steps": [
          [
            1,
            10,
            1
          ],
          [
            1,
            10,
            1
          ],
          [
            1,
            10,
            1
          ],
          [
            10,
            20,
            1
          ],
          [
            20,
            50,
            2
          ],
          [
            50,
            100,
            2
          ],
          [
            100,
            199,
            3
          ]
        ]
      },
      "condenserEffect": {
        "name": "Condenser Effect",
        "currentBonus": 23.5,
        "steps": [
          -1,
          [
            1,
            5,
            0.25
          ],
          [
            1,
            5,
            0.25
          ],
          [
            5,
            10,
            0.25
          ],
          [
            5,
            15,
            0.5
          ],
          [
            10,
            20,
            0.5
          ],
          [
            20,
            30,
            0.5
          ]
        ],
        "max": [
          -1,
          10,
          10,
          15,
          25,
          35,
          50
        ]
      }
    },
    "Staff": {
      "metalDrop": {
        "name": "Metal Drop Rate",
        "currentBonus": 0
      },
      "foodDrop": {
        "name": "Food Drop Rate",
        "currentBonus": 0
      },
      "woodDrop": {
        "name": "Wood Drop Rate",
        "currentBonus": 0
      },
      "gemsDrop": {
        "name": "Gem Drop Rate",
        "currentBonus": 832
      },
      "fragmentsDrop": {
        "name": "Fragment Drop Rate",
        "currentBonus": 10624
      },
      "FarmerSpeed": {
        "name": "Farmer Efficiency",
        "currentBonus": 5568
      },
      "LumberjackSpeed": {
        "name": "Lumberjack Efficiency",
        "currentBonus": 0
      },
      "MinerSpeed": {
        "name": "Miner Efficiency",
        "currentBonus": 10752
      },
      "DragimpSpeed": {
        "name": "Dragimp Efficiency",
        "currentBonus": 0
      },
      "ExplorerSpeed": {
        "name": "Explorer Efficiency",
        "currentBonus": 0
      },
      "ScientistSpeed": {
        "name": "Scientist Efficiency",
        "currentBonus": 10624
      },
      "FluffyExp": {
        "heirloopy": true,
        "currentBonus": 310,
        "steps": [
          -1,
          -1,
          -1,
          -1,
          -1,
          -1,
          -1,
          -1,
          [
            25,
            50,
            1
          ],
          [
            50,
            100,
            1
          ],
          [
            75,
            200,
            1
          ]
        ]
      },
      "empty": {
        "name": "Empty",
        "currentBonus": 0
      }
    },
    "Shield": {
      "playerEfficiency": {
        "name": "Player Efficiency",
        "currentBonus": 0,
        "steps": [
          [
            8,
            16,
            1
          ],
          [
            8,
            16,
            1
          ],
          [
            8,
            16,
            1
          ],
          [
            16,
            32,
            2
          ],
          [
            32,
            64,
            4
          ],
          [
            64,
            128,
            8
          ],
          [
            128,
            256,
            16
          ],
          [
            256,
            512,
            32
          ],
          [
            512,
            1024,
            64
          ],
          [
            1024,
            2048,
            128
          ],
          [
            2048,
            4096,
            256
          ]
        ]
      },
      "trainerEfficiency": {
        "name": "Trainer Efficiency",
        "currentBonus": 0,
        "steps": [
          [
            10,
            20,
            1
          ],
          [
            10,
            20,
            1
          ],
          [
            10,
            20,
            1
          ],
          [
            20,
            40,
            2
          ],
          [
            40,
            60,
            2
          ],
          [
            60,
            80,
            2
          ],
          [
            80,
            100,
            2
          ],
          [
            100,
            120,
            2
          ],
          [
            120,
            140,
            2
          ],
          -1,
          -1
        ]
      },
      "storageSize": {
        "name": "Storage Size",
        "currentBonus": 0,
        "steps": [
          [
            32,
            64,
            4
          ],
          [
            32,
            64,
            4
          ],
          [
            32,
            64,
            4
          ],
          [
            64,
            128,
            4
          ],
          [
            128,
            256,
            8
          ],
          [
            256,
            512,
            16
          ],
          [
            512,
            768,
            16
          ],
          [
            768,
            1024,
            16
          ],
          [
            1024,
            1280,
            16
          ],
          -1,
          -1
        ]
      },
      "breedSpeed": {
        "name": "Breed Speed",
        "currentBonus": 0,
        "steps": [
          [
            5,
            10,
            1
          ],
          [
            5,
            10,
            1
          ],
          [
            5,
            10,
            1
          ],
          [
            10,
            20,
            1
          ],
          [
            70,
            100,
            3
          ],
          [
            100,
            130,
            3
          ],
          [
            130,
            160,
            3
          ],
          [
            160,
            190,
            3
          ],
          [
            190,
            220,
            3
          ],
          [
            220,
            280,
            5
          ],
          [
            260,
            360,
            10
          ]
        ]
      },
      "trimpHealth": {
        "name": "Trimp Health",
        "currentBonus": 2130,
        "steps": [
          [
            6,
            20,
            2
          ],
          [
            6,
            20,
            2
          ],
          [
            6,
            20,
            2
          ],
          [
            20,
            40,
            2
          ],
          [
            50,
            100,
            5
          ],
          [
            100,
            150,
            5
          ],
          [
            150,
            200,
            5
          ],
          [
            200,
            260,
            6
          ],
          [
            260,
            356,
            8
          ],
          [
            360,
            460,
            10
          ],
          [
            600,
            750,
            10
          ]
        ]
      },
      "trimpAttack": {
        "name": "Trimp Attack",
        "currentBonus": 2130,
        "steps": [
          [
            6,
            20,
            2
          ],
          [
            6,
            20,
            2
          ],
          [
            6,
            20,
            2
          ],
          [
            20,
            40,
            2
          ],
          [
            50,
            100,
            5
          ],
          [
            100,
            150,
            5
          ],
          [
            150,
            200,
            5
          ],
          [
            200,
            260,
            6
          ],
          [
            260,
            356,
            8
          ],
          [
            360,
            460,
            10
          ],
          [
            600,
            750,
            10
          ]
        ]
      },
      "trimpBlock": {
        "name": "Trimp Block",
        "currentBonus": 0,
        "steps": [
          [
            4,
            7,
            1
          ],
          [
            4,
            7,
            1
          ],
          [
            4,
            7,
            1
          ],
          [
            7,
            10,
            1
          ],
          [
            28,
            40,
            1
          ],
          [
            48,
            60,
            1
          ],
          [
            68,
            80,
            1
          ],
          [
            88,
            100,
            1
          ],
          [
            108,
            120,
            1
          ],
          -1,
          -1
        ]
      },
      "critDamage": {
        "name": "Crit Damage, additive",
        "currentBonus": 3950,
        "steps": [
          [
            40,
            60,
            5
          ],
          [
            40,
            60,
            5
          ],
          [
            40,
            60,
            5
          ],
          [
            60,
            100,
            5
          ],
          [
            100,
            200,
            10
          ],
          [
            200,
            300,
            10
          ],
          [
            300,
            400,
            10
          ],
          [
            400,
            500,
            10
          ],
          [
            500,
            650,
            15
          ],
          [
            650,
            850,
            20
          ],
          [
            850,
            1100,
            25
          ]
        ]
      },
      "critChance": {
        "name": "Crit Chance, additive",
        "currentBonus": 123.75,
        "heirloopy": true,
        "steps": [
          [
            1.4,
            2.6,
            0.2
          ],
          [
            1.4,
            2.6,
            0.2
          ],
          [
            1.4,
            2.6,
            0.2
          ],
          [
            2.6,
            5,
            0.2
          ],
          [
            5,
            7.4,
            0.2
          ],
          [
            7.4,
            9.8,
            0.2
          ],
          [
            9.8,
            12.2,
            0.2
          ],
          [
            12.3,
            15.9,
            0.3
          ],
          [
            20,
            30,
            0.5
          ],
          [
            30,
            50,
            0.5
          ],
          [
            50,
            80,
            0.25
          ]
        ],
        "max": [
          30,
          30,
          30,
          30,
          30,
          30,
          30,
          30,
          100,
          125,
          200
        ]
      },
      "voidMaps": {
        "name": "Void Map Drop Chance",
        "currentBonus": 0,
        "heirloopy": true,
        "steps": [
          [
            5,
            7,
            0.5
          ],
          [
            5,
            7,
            0.5
          ],
          [
            5,
            7,
            0.5
          ],
          [
            8,
            11,
            0.5
          ],
          [
            12,
            16,
            0.5
          ],
          [
            17,
            22,
            0.5
          ],
          [
            24,
            30,
            0.5
          ],
          [
            32,
            38,
            0.5
          ],
          [
            40,
            50,
            0.25
          ],
          [
            50,
            60,
            0.25
          ],
          [
            5,
            7,
            0.1
          ]
        ],
        "max": [
          50,
          50,
          50,
          50,
          50,
          50,
          50,
          50,
          80,
          99,
          40
        ]
      },
      "plaguebringer": {
        "name": "Plaguebringer",
        "currentBonus": 106.5,
        "heirloopy": true,
        "steps": [
          -1,
          -1,
          -1,
          -1,
          -1,
          -1,
          -1,
          -1,
          [
            1,
            15,
            0.5
          ],
          [
            15,
            30,
            0.5
          ],
          [
            30,
            45,
            0.5
          ]
        ],
        "max": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          75,
          100,
          125
        ]
      },
      "prismatic": {
        "name": "Prismatic Shield",
        "currentBonus": 156,
        "noScaleU2": true,
        "steps": [
          -1,
          -1,
          -1,
          -1,
          -1,
          -1,
          -1,
          -1,
          -1,
          [
            10,
            50,
            1
          ],
          [
            10,
            40,
            1
          ]
        ],
        "max": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          250,
          500
        ]
      },
      "gammaBurst": {
        "name": "Gamma Burst",
        "currentBonus": 0,
        "stacks": 2,
        "steps": [
          -1,
          -1,
          -1,
          -1,
          -1,
          -1,
          -1,
          -1,
          -1,
          [
            1000,
            2000,
            100
          ],
          -1
        ]
      },
      "empty": {
        "name": "Empty",
        "currentBonus": 0,
        "rarity": 1
      }
    }
  }